#!/bin/sh
#
# Copyright (c) 2010, 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0, which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# This Source Code may also be made available under the following Secondary
# Licenses when the conditions for such availability set forth in the
# Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
# version 2 with the GNU Classpath Exception, which is available at
# https://www.gnu.org/software/classpath/license.html.
#
# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
#

#
# Generate a new signature file.
#
# Usage: siggen javax.mail.jar mail.sig
#
SIGTEST=${SIGTEST:-/java/re/sigtest/4.0/promoted/fcs/latest/binaries/sigtest-4.0}
SIGTEST_JAR=$SIGTEST/lib/sigtestdev.jar
JAVA_HOME=${JAVA_HOME:-/opt/jdk1.8}
PKG=javax.mail
USAGE="siggen [-p package] javax.mail.jar mail.sig"

while getopts p: opt
do
	case $opt in
	p)	PKG="$OPTARG";;
	\?)	echo $USAGE; exit 1;;
	esac
done
shift `expr $OPTIND - 1`

ver=$($JAVA_HOME/bin/java -version 2>&1 | sed -e 's/.*"\(.*\)".*/\1/;q')
case "$ver" in
1.[0-9]*)	xjimage=;
		cp="$1:${JAVA_HOME}/jre/lib/rt.jar:${JAVA_HOME}/jre/lib/jce.jar";;
*)		xjimage="-xjimage ${JAVA_HOME}/bin/jimage";
		cp="$1:${JAVA_HOME}/lib/modules";;
esac

${JAVA_HOME}/bin/java -jar $SIGTEST_JAR setup -static \
	-classpath "$cp" $xjimage \
	-filename "$2" -package "$PKG" -nonclosedfile
